name: Publish a release to crates.io

on:
  push:
    branches:
      - 'main'
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  upload-crate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: cargo publish

    
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - uses: actions-rs/cargo@v1
      env:
        CARGO_TOKEN: ${{ secrets.CARGO_TOKEN }}
      with:
        command: publish
        args: --token $CARGO_TOKEN